trigger:
- main

variables:

  azureSubscription: '9a3cafdc-1e49-4ce8-8c1d-69ee7372ac57'
  webAppName: 'tiptipback'

  # Environments
  prodEnvironment: 'tiptipback-prod'
  recetteEnvironment: 'tiptipback-recette'

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build --if-present
      displayName: 'npm install, build and test'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

# Prod
- stage: DeployProd
  displayName: Deploy Prod stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployProd
    displayName: Deploy Prod
    environment: $(prodEnvironment)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: tiptipback (Prod)'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|16.0'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start'


# Preprod
- stage: DeployRecette
  displayName: Deploy Recette stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployRecette
    displayName: Deploy Recette
    environment: $(recetteEnvironment)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: tiptipback (Recette)'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|16.0'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startUpCommand: 'npm run start'
